apiVersion: v1
kind: Service
metadata:
  name: message-app
spec:
  selector:
    app: message-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  env:
    - name: REACT_APP_API_URL
      value: "notification-service:8080"
